# Generated by Django 4.1.7 on 2023-03-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\\t)'), (' ', 'Space ( )'), ('|', 'Pipe (|)')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], default='"', max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Processing', 'Double-quote (")'), ('Ready', "Single-quote (')")], default='Processing', max_length=10)),
                ('records', models.IntegerField(default=500)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='generated_files/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_csv_maker.dataschema')),
            ],
        ),
        migrations.CreateModel(
            name='DataSchemaColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full name', 'Full Name'), ('Job', 'Job'), ('Email', 'Email'), ('Domain', 'Domain'), ('Phone number', 'Phone Number'), ('Company', 'Company'), ('Text', 'Text'), ('Integer', 'Integer'), ('Address', 'Address'), ('Date', 'Date')], max_length=255)),
                ('range_start', models.IntegerField(blank=True, null=True)),
                ('range_end', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='fake_csv_maker.dataschema')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dataschemacolumn',
            constraint=models.UniqueConstraint(fields=('order', 'schema'), name='unique_order_per_schema'),
        ),
    ]
