# Generated by Django 4.1.7 on 2023-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dataschemacolumn',
            constraint=models.UniqueConstraint(fields=('order', 'schema'), name='unique_order_per_schema'),
        ),
    ]
