# Generated by Django 4.1.7 on 2023-03-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_csv_maker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataschemacolumn',
            old_name='name',
            new_name='column_name',
        ),
    ]
